# Generated by Django 5.2.4 on 2025-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trainer_id', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=50)),
                ('personal_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('domain', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Trainer', 'Trainer'), ('Trainee', 'Trainee')], max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
            ],
        ),
    ]
